### PR TITLE
Create Resources.zh-CN.resx

### PR DESCRIPTION
**Pull request by peter9811**
Chinese Simplified translation
Credits: Dwhite Reeves (duzhe163908)

### CODE REVIEW

**Comment by Belim** [comment]
I wonder how many languages you speak :grin: 
The gui looks good, even some strings are not translated yet but I am really amazed how fast you are

Privatezilla_NUfXTEleJM

**Comment by peter9811** [comment]
@Belim 
No, no no. I didn't translate this language.
All credits to: Dwhite Reeves (duzhe163908) (https://crowdin.com/project/privatezilla-traduccin/zh-CN#)

Maybe it's necessary too translate the `MainWindow.resx`, because I deleted from the web

So weird... The strings are translated to 100 %...

**Comment by Belim** [comment]
My mistake, it was a bug in the code :grimacing:
I've pushed a fix and now everything is as it should be

Feel free to put a note on crodwin with a hint that credits can be added via `infoApp` string

Many thanks for your support.

**Comment by Belim** [comment]
Is there any possibility to provide download links to the language files without creating an account on crodwin?
Otherwise i will offer them in this repo for download optionally as Iam considering not including them by default.

**Comment by peter9811** [comment]
@Belim 
image
You can download the translation without a account, but you can't help to translate without one

**Comment by peter9811** [comment]
> Feel free to put a note on crodwin with a hint that credits can be added via `infoApp` string
> 
> Many thanks for your support.

I add a little space to add credits: `Translation credits to: put your information, name, email here!` on the `infoApp` string...

**Pull request merged**
